cardinal_1 = imread('cardinal1.jpg');
% cardinal_1 = rgb2gray( cardinal_1 );
cardinal_1 = imresize( cardinal_1, [100, 100] );


cardinal_2 = imread('cardinal2.jpg');
% cardinal_2 = rgb2gray( cardinal_2 );
cardinal_2 = imresize( cardinal_2, [100, 100] );

leopard_1 = imread('leopard1.jpg');
% leopard_1 = rgb2gray( leopard_1 );
leopard_1 = imresize( leopard_1, [100, 100] );

leopard_2 = imread('leopard2.jpg');
% leopard_2 = rgb2gray( leopard_2 );
leopard_2 = imresize( leopard_2, [100, 100] );


panda_1 = imread('panda1.jpg');
% panda_1 = rgb2gray( panda_1 );
panda_1 = imresize( panda_1, [100, 100] );

panda_2 = imread('panda2.jpg');
% panda_2 = rgb2gray( panda_2 );
panda_2 = imresize( panda_2, [100, 100] );


means = load('means.mat');
means = means.means;


[bow_repr_cardinal1, texture_repr_concat_cardinal1, texture_repr_mean_cardinal1] = ...
    compute_image_repr( cardinal_1, means, filters);
[bow_repr_cardinal2, texture_repr_concat_cardinal2, texture_repr_mean_cardinal2] = ...
    compute_image_repr( cardinal_2, means, filters);

[bow_repr_leopard1, texture_repr_concat_leopard1, texture_repr_mean_leopard1] = ...
    compute_image_repr( leopard_1, means, filters);
[bow_repr_leopard2, texture_repr_concat_leopard2, texture_repr_mean_leopard2] = ...
    compute_image_repr( leopard_2, means, filters);

[bow_repr_panda1, texture_repr_concat_panda1, texture_repr_mean_panda1] = ...
    compute_image_repr( panda_1, means, filters);
[bow_repr_panda2, texture_repr_concat_panda2, texture_repr_mean_panda2] = ...
    compute_image_repr( panda_2, means, filters);


average_within_class_distance_bow_repr = sum( [ compute_distance( bow_repr_cardinal1, bow_repr_cardinal2),...
    compute_distance( bow_repr_leopard1, bow_repr_leopard2),...
    compute_distance( bow_repr_panda1, bow_repr_panda2) ] )/3;

average_between_class_distance_bow_repr = sum( [compute_distance( bow_repr_cardinal1, bow_repr_leopard1),...
    compute_distance( bow_repr_cardinal1, bow_repr_leopard2),...
    compute_distance( bow_repr_cardinal1, bow_repr_panda1),compute_distance( bow_repr_cardinal1, bow_repr_panda2),...
    compute_distance( bow_repr_cardinal2, bow_repr_leopard1),compute_distance( bow_repr_cardinal2, bow_repr_leopard2),...
    compute_distance( bow_repr_cardinal2, bow_repr_panda1),compute_distance( bow_repr_cardinal2, bow_repr_panda2),...
    compute_distance( bow_repr_leopard1, bow_repr_panda1), compute_distance(bow_repr_leopard1, bow_repr_panda2),...
    compute_distance( bow_repr_leopard2, bow_repr_panda1), compute_distance(bow_repr_leopard2, bow_repr_panda2)] )/12;
    


average_within_class_distance_repr_concat = sum( [ compute_distance( texture_repr_concat_cardinal1, texture_repr_concat_cardinal2),...
    compute_distance( texture_repr_concat_leopard1, texture_repr_concat_leopard2),...
    compute_distance( texture_repr_concat_panda1, texture_repr_concat_panda2) ] )/3;

average_between_class_distance_repr_concat = sum( [compute_distance( texture_repr_concat_cardinal1, texture_repr_concat_leopard1),...
    compute_distance( texture_repr_concat_cardinal1, texture_repr_concat_leopard2),...
    compute_distance( texture_repr_concat_cardinal1, texture_repr_concat_panda1),compute_distance( texture_repr_concat_cardinal1, texture_repr_concat_panda2),...
    compute_distance( texture_repr_concat_cardinal2, texture_repr_concat_leopard1),compute_distance( texture_repr_concat_cardinal2, texture_repr_concat_leopard2),...
    compute_distance( texture_repr_concat_cardinal2, texture_repr_concat_panda1),compute_distance( texture_repr_concat_cardinal2, texture_repr_concat_panda2),...
    compute_distance( texture_repr_concat_leopard1, texture_repr_concat_panda1), compute_distance(texture_repr_concat_leopard1, texture_repr_concat_panda2),...
    compute_distance( texture_repr_concat_leopard2, texture_repr_concat_panda1), compute_distance(texture_repr_concat_leopard2, texture_repr_concat_panda2)] )/12;



average_within_class_distance_repr_mean = sum( [ compute_distance( texture_repr_mean_cardinal1, texture_repr_mean_cardinal2),...
    compute_distance( texture_repr_mean_leopard1, texture_repr_mean_leopard2),...
    compute_distance( texture_repr_mean_panda1, texture_repr_mean_panda2) ] )/3;

average_between_class_distance_repr_mean = sum( [compute_distance( texture_repr_mean_cardinal1, texture_repr_mean_leopard1),...
    compute_distance( texture_repr_mean_cardinal1, texture_repr_mean_leopard2),...
    compute_distance( texture_repr_mean_cardinal1, texture_repr_mean_panda1),compute_distance( texture_repr_mean_cardinal1, texture_repr_mean_panda2),...
    compute_distance( texture_repr_mean_cardinal2, texture_repr_mean_leopard1),compute_distance( texture_repr_mean_cardinal2, texture_repr_mean_leopard2),...
    compute_distance( texture_repr_mean_cardinal2, texture_repr_mean_panda1),compute_distance( texture_repr_mean_cardinal2, texture_repr_mean_panda2),...
    compute_distance( texture_repr_mean_leopard1, texture_repr_mean_panda1), compute_distance(texture_repr_mean_leopard1, texture_repr_mean_panda2),...
    compute_distance( texture_repr_mean_leopard2, texture_repr_mean_panda1), compute_distance(texture_repr_mean_leopard2, texture_repr_mean_panda2)] )/12;


% 
% 
% average_within_class_distance_bow_repr = sum( [ bow_repr_cardinal1*bow_repr_cardinal2',...
%     bow_repr_leopard1*bow_repr_leopard2', bow_repr_panda1*bow_repr_panda2'] )/3;
% average_between_class_distance_bow_repr = sum( [ bow_repr_cardinal1*bow_repr_leopard1',...
%     bow_repr_cardinal1*bow_repr_leopard2', bow_repr_cardinal1*bow_repr_panda1', ...
%     bow_repr_cardinal1*bow_repr_panda2', bow_repr_cardinal2*bow_repr_leopard1',...
%     bow_repr_cardinal2*bow_repr_leopard2', bow_repr_cardinal2*bow_repr_panda1', ...
%     bow_repr_cardinal2*bow_repr_panda2', ...
%     bow_repr_leopard1*bow_repr_panda1', bow_repr_leopard1*bow_repr_panda2',... 
%     bow_repr_leopard2*bow_repr_panda1', bow_repr_leopard2*bow_repr_panda2'] )/12;
% 
% 
% average_within_class_distance_texture_concat = sum( [texture_repr_concat_cardinal1*texture_repr_concat_cardinal2',...
%     texture_repr_concat_leopard1*texture_repr_concat_leopard2', texture_repr_concat_panda1*texture_repr_concat_panda2'] )/3;
% 
% average_between_class_distance_texture_concat =sum( [ texture_repr_concat_cardinal1*texture_repr_concat_leopard1',...
%     texture_repr_concat_cardinal1*texture_repr_concat_leopard2', texture_repr_concat_cardinal1*texture_repr_concat_panda1', ...
%     texture_repr_concat_cardinal1*texture_repr_concat_panda2', texture_repr_concat_cardinal2*texture_repr_concat_leopard1',...
%     texture_repr_concat_cardinal2*texture_repr_concat_leopard2', texture_repr_concat_cardinal2*texture_repr_concat_panda1', ...
%     texture_repr_concat_cardinal2*texture_repr_concat_panda2', ...
%     texture_repr_concat_leopard1*texture_repr_concat_panda1', texture_repr_concat_leopard1*texture_repr_concat_panda2',... 
%     texture_repr_concat_leopard2*texture_repr_concat_panda1', texture_repr_concat_leopard2*texture_repr_concat_panda2'] )/12;
% 
% 
% 
% average_within_class_distance_texture_mean = sum( [texture_repr_mean_cardinal1*texture_repr_mean_cardinal2',...
%     texture_repr_mean_leopard1*texture_repr_mean_leopard2', texture_repr_mean_panda1*texture_repr_mean_panda2'] )/3;
% 
% average_between_class_distance_texture_mean =sum( [ texture_repr_mean_cardinal1*texture_repr_mean_leopard1',...
%     texture_repr_mean_cardinal1*texture_repr_mean_leopard2', texture_repr_mean_cardinal1*texture_repr_mean_panda1', ...
%     texture_repr_mean_cardinal1*texture_repr_mean_panda2', texture_repr_mean_cardinal2*texture_repr_mean_leopard1',...
%     texture_repr_mean_cardinal2*texture_repr_mean_leopard2', texture_repr_mean_cardinal2*texture_repr_mean_panda1', ...
%     texture_repr_mean_cardinal2*texture_repr_mean_panda2', ...
%     texture_repr_mean_leopard1*texture_repr_mean_panda1', texture_repr_mean_leopard1*texture_repr_mean_panda2',... 
%     texture_repr_mean_leopard2*texture_repr_mean_panda1', texture_repr_mean_leopard2*texture_repr_mean_panda2'] )/12;
% 
ratio = [ average_within_class_distance_bow_repr/average_between_class_distance_bow_repr,...
    average_within_class_distance_repr_concat/average_between_class_distance_repr_concat,...
    average_within_class_distance_repr_mean/average_between_class_distance_repr_mean];
